services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "billger"
    ports:
      - "15432:5432"
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge